### ISSUE TITLE
Remove deprecated functions from templates

### ISSUE THREAD

**Issue by eddiewebb** [FriendsOfFlarum/pretty-mail#21]
## Bug Report

**Current Behavior**
Templates still use `{!! app()->url() !!}` which is invalid in 16+ and thows error

` Call to undefined method Illuminate\Container\Container::url()`

**Steps to Reproduce**
1. Use default tempaltes, specifially the "user mentioned" which contains the `{!! app()->url() !!}` as part of discussion link
2. Add a post/comment
3. Error in UI, email never sends, and worse `afterUpdate` events like reindex never called.

**Expected Behavior**
Expect clean error and post-update functions to still ruin.

**Screenshots**
![Screen Shot 2021-05-25 at 1 28 04 PM](https://user-images.githubusercontent.com/5262154/119543199-655b7480-bd5e-11eb-9a17-2498633fef24.png)

\

**Environment**
- Flarum version: 0.16-beta
- Extension version: 0.4.0
- Website URL: https://adkadv.com

**Possible solution(s)**
remove or repalce that call in template

**Comment by eddiewebb** [comment]
From beta 14 upgrade guide:

> The app helper now points to an instance of Illuminate\Container\Container, not Flarum\Foundation\Application. You might need to resolve things through the container before using them: for instance, app()->url() will no longer work; you'll need to resolve or inject an instance of Flarum\Foundation\Config and use that.

**Comment by imorland** [comment]
This was updated previously

https://github.com/FriendsOfFlarum/pretty-mail/blob/3b880b12d4432d4761f96a396975d39b43015d15/js/src/admin/defaults.js#L89

and

https://github.com/FriendsOfFlarum/pretty-mail/blob/3b880b12d4432d4761f96a396975d39b43015d15/resources/defaults/mailhtml.blade.php#L39

And announced here https://discuss.flarum.org/d/11178-friendsofflarum-pretty-mail/121

I *think* the issue you are seeing may be due to old templates being held in the db. They're stored in the `settings` table. You could try resetting the templates to defaults, which should solve the problem you see here.

That said, I intend to refactor this extension in the next day or two ready for Flarum v1.0, and have some changes in mind to the templating system used by this extension to bring it more in line with standard Laravel templates (using partials as much as possible)

**Comment by eddiewebb** [comment]
Doh!  Yes perfect thank you and sorry!

**Comment by imorland** [comment]
No problem at all :)
